services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PORT: ${PORT}
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env.development
    depends_on:
      - database
      - redis
      - rabbitmq
      - installer
    volumes:
      - ./:/app:cached
      - node_modules:/app/node_modules

  redis:
    image: redis:latest
    ports:
      - '6380:6379'
    volumes:
      - redisdata:/data

  database:
    image: postgres:15-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - '5673:5672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
      - rabbitmqlogs:/var/log/rabbitmq

  installer:
    image: node:22.12.0-alpine
    working_dir: /app
    volumes:
      - ./:/app:cached
      - node_modules:/app/node_modules
    command: sh -c "corepack enable && corepack prepare yarn@stable --activate && yarn install --immutable"
    restart: 'no'

volumes:
  node_modules:
  redisdata:
  pgdata:
  rabbitmqdata:
  rabbitmqlogs:
