FROM node:22.12.0-alpine

WORKDIR /app

# Copy only dependency files first
# COPY package.json yarn.lock ./

# RUN corepack enable && corepack prepare yarn@4.9.4 --activate

# Install dependencies (cached if unchanged)
# RUN yarn install --frozen-lockfile

# Copy the rest of the source code
COPY . .

CMD ["yarn", "dev"]

EXPOSE ${PORT}
