services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PORT: ${PORT}
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env.development
    depends_on:
      - database
      - redis
      - rabbitmq

  redis:
    image: redis:latest
    ports:
      - '6380:6379' # host:container

  database:
    image: postgres:15-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - '5673:5672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
